/**
 * Centralized enums for the audit system.
 * REQ-AUD-008, REQ-AUD-009
 */

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  ACCESS_DENIED = 'ACCESS_DENIED',
  DOWNLOAD = 'DOWNLOAD',
  EXPORT = 'EXPORT',
  PRINT = 'PRINT',
  SHARE = 'SHARE',
  UNSHARE = 'UNSHARE',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
}

export enum AuditResourceType {
  PATIENT = 'PATIENT',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  MEDICAL_EVOLUTION = 'MEDICAL_EVOLUTION',
  PRESCRIPTION = 'PRESCRIPTION',
  EXAM = 'EXAM',
  DIAGNOSIS = 'DIAGNOSIS',
  ALLERGY = 'ALLERGY',
  VACCINE = 'VACCINE',
  DISEASE = 'DISEASE',
  DOCUMENT = 'DOCUMENT',
  ATTACHMENT = 'ATTACHMENT',
  APPOINTMENT = 'APPOINTMENT',
  MEDICATION = 'MEDICATION',
  PROFESSIONAL = 'PROFESSIONAL',
  USER = 'USER',
  CONSENT = 'CONSENT',
  CLINIC = 'CLINIC',
  DEPENDENT = 'DEPENDENT',
  AUDIT_EVENT = 'AUDIT_EVENT',
}

export enum AuditFailureReason {
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  INVALID_STATE = 'INVALID_STATE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
